"""Workspace initialization command."""

import shutil
from pathlib import Path

import typer


def init(
    workspace_name: str,
    force: bool = typer.Option(False, "--force"),
) -> None:
    """Create a new TASC workspace."""
    workspace_path = Path(workspace_name)

    if workspace_path.exists():
        if not force:
            typer.echo(
                f"Workspace '{workspace_name}' already exists. "
                "Use --force to overwrite it.",
                err=True,
            )
            raise typer.Exit(code=1)
        if workspace_path.is_dir():
            shutil.rmtree(workspace_path)
        else:
            workspace_path.unlink()

    (workspace_path / "config").mkdir(parents=True)
    (workspace_path / "projects").mkdir()
    (workspace_path / "agents").mkdir()
    (workspace_path / "logs").mkdir()

    (workspace_path / "workspace.yaml").write_text(
        "apiVersion: tasc.io/v1alpha1\n"
        "kind: Workspace\n"
        "\n"
        "metadata:\n"
        f"  name: {workspace_name}\n",
        encoding="utf-8",
    )
    (workspace_path / "config" / "core.yaml").write_text(
        "apiVersion: tasc.io/v1alpha1\n"
        "kind: CoreConfiguration\n"
        "\n"
        "metadata:\n"
        f"  name: {workspace_name}\n"
        "  version: 0.1.0\n"
        "  description: TASC Builder workspace configuration\n"
        "\n"
        "company:\n"
        f"  name: {workspace_name}\n"
        "  domain: example.com\n"
        "  contact_email: ops@example.com\n"
        "\n"
        "runtime:\n"
        "  environment: development\n"
        "  version: 0.1.0\n"
        "\n"
        "logging:\n"
        "  level: INFO\n"
        "  format: plain\n"
        "\n"
        "modules:\n"
        "  enabled:\n"
        "    - core\n"
        "\n"
        "providers:\n"
        "  name: default\n"
        "  kind: placeholder\n"
        "\n"
        "bootstrap:\n"
        "  enabled: true\n",
        encoding="utf-8",
    )
    (workspace_path / "README.md").write_text(
        f"# {workspace_name}\n\nGenerated by TASC Builder.\n",
        encoding="utf-8",
    )

    typer.echo(f"Workspace '{workspace_name}' created.")
