from __future__ import annotations

import os
import sys
import unittest
from datetime import datetime, timezone
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

from typer.testing import CliRunner

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "core"))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "projects"))

from tasc_cli.app import app
from tasc_core.exceptions import (
    BootstrapException,
    ConfigurationException,
    ValidationException,
)
from tasc_projects.exceptions import ProjectException
from tasc_projects.models import Project, ProjectConfiguration, ProjectMetadata


class CliTests(unittest.TestCase):
    def setUp(self) -> None:
        self.runner = CliRunner()

    def test_cli_starts_successfully(self) -> None:
        result = self.runner.invoke(app)

        self.assertEqual(result.exit_code, 0)

    def test_help_works(self) -> None:
        result = self.runner.invoke(app, ["--help"])

        self.assertEqual(result.exit_code, 0)

    def test_commands_exist(self) -> None:
        result = self.runner.invoke(app, ["--help"])

        self.assertIn("init", result.output)
        self.assertIn("validate", result.output)
        self.assertIn("bootstrap", result.output)
        self.assertIn("doctor", result.output)

    def test_init_command_creates_workspace(self) -> None:
        with TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir) / "my-company"
            result = self.runner.invoke(app, ["init", str(workspace)])

            self.assertEqual(result.exit_code, 0)
            self.assertTrue(workspace.is_dir())
            self.assertTrue((workspace / "config" / "core.yaml").is_file())
            self.assertTrue((workspace / "projects").is_dir())
            self.assertTrue((workspace / "agents").is_dir())
            self.assertTrue((workspace / "logs").is_dir())
            self.assertTrue((workspace / "README.md").is_file())
            self.assertEqual(
                (workspace / "workspace.yaml").read_text(encoding="utf-8"),
                "apiVersion: tasc.io/v1alpha1\n"
                "kind: Workspace\n"
                "\n"
                "metadata:\n"
                f"  name: {workspace}\n",
            )
            self.assertEqual(
                (workspace / "README.md").read_text(encoding="utf-8"),
                f"# {workspace}\n\nGenerated by TASC Builder.\n",
            )
            self.assertEqual(
                {path.relative_to(workspace) for path in workspace.rglob("*")},
                {
                    Path("agents"),
                    Path("config"),
                    Path("config/core.yaml"),
                    Path("logs"),
                    Path("projects"),
                    Path("README.md"),
                    Path("workspace.yaml"),
                },
            )

    def test_init_workspace_validates_without_manual_edits(self) -> None:
        with TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir) / "my-company"
            init_result = self.runner.invoke(app, ["init", str(workspace)])

            original_directory = Path.cwd()
            try:
                os.chdir(workspace)
                validate_result = self.runner.invoke(app, ["validate"])
            finally:
                os.chdir(original_directory)

        self.assertEqual(init_result.exit_code, 0)
        self.assertEqual(validate_result.exit_code, 0)
        self.assertEqual(validate_result.output, "Configuration is valid.\n")

    def test_init_command_rejects_existing_workspace_without_force(self) -> None:
        with TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir) / "my-company"
            workspace.mkdir()

            result = self.runner.invoke(app, ["init", str(workspace)])

            self.assertNotEqual(result.exit_code, 0)
            self.assertIn("already exists", result.output)

    def test_init_command_overwrites_existing_workspace_with_force(self) -> None:
        with TemporaryDirectory() as temp_dir:
            workspace = Path(temp_dir) / "my-company"
            workspace.mkdir()
            (workspace / "existing.txt").write_text("old", encoding="utf-8")

            result = self.runner.invoke(app, ["init", str(workspace), "--force"])

            self.assertEqual(result.exit_code, 0)
            self.assertFalse((workspace / "existing.txt").exists())
            self.assertTrue((workspace / "config" / "core.yaml").is_file())

    def test_validate_command(self) -> None:
        with (
            patch("tasc_cli.commands.validate.ConfigurationLoader") as loader_class,
            patch("tasc_cli.commands.validate.ConfigurationParser") as parser_class,
            patch(
                "tasc_cli.commands.validate.ConfigurationValidator"
            ) as validator_class,
        ):
            loader_class.return_value.load.return_value = "apiVersion: tasc.io/v1alpha1"
            parser_class.return_value.parse.return_value = {}

            result = self.runner.invoke(app, ["validate"])

        self.assertEqual(result.exit_code, 0)
        self.assertEqual(result.output, "Configuration is valid.\n")
        loader_class.return_value.load.assert_called_once_with(Path("config/core.yaml"))
        parser_class.return_value.parse.assert_called_once_with(
            "apiVersion: tasc.io/v1alpha1"
        )
        validator_class.return_value.validate.assert_called_once_with({})

    def test_validate_command_reports_invalid_configuration(self) -> None:
        with (
            patch("tasc_cli.commands.validate.ConfigurationLoader") as loader_class,
            patch("tasc_cli.commands.validate.ConfigurationParser") as parser_class,
            patch(
                "tasc_cli.commands.validate.ConfigurationValidator"
            ) as validator_class,
        ):
            loader_class.return_value.load.return_value = "invalid"
            parser_class.return_value.parse.return_value = {}
            validator_class.return_value.validate.side_effect = ValidationException(
                "Invalid configuration",
                "TASC-VALIDATION-0001",
            )

            result = self.runner.invoke(app, ["validate"])

        self.assertNotEqual(result.exit_code, 0)
        self.assertIn("Invalid configuration", result.output)

    def test_validate_command_reports_missing_configuration_file(self) -> None:
        with patch("tasc_cli.commands.validate.ConfigurationLoader") as loader_class:
            loader_class.return_value.load.side_effect = ConfigurationException(
                "File not found",
                "TASC-CONFIG-0001",
            )

            result = self.runner.invoke(app, ["validate"])

        self.assertNotEqual(result.exit_code, 0)
        self.assertIn("Configuration file not found", result.output)

    def test_validate_command_uses_explicit_config_path(self) -> None:
        config_path = Path("custom/core.yaml")
        with (
            patch("tasc_cli.commands.validate.ConfigurationLoader") as loader_class,
            patch("tasc_cli.commands.validate.ConfigurationParser") as parser_class,
            patch(
                "tasc_cli.commands.validate.ConfigurationValidator"
            ) as validator_class,
        ):
            loader_class.return_value.load.return_value = "configuration"
            parser_class.return_value.parse.return_value = {}

            result = self.runner.invoke(app, ["validate", "--config", str(config_path)])

        self.assertEqual(result.exit_code, 0)
        loader_class.return_value.load.assert_called_once_with(config_path)

    def test_bootstrap_command(self) -> None:
        with patch("tasc_cli.commands.bootstrap.BootstrapEngine") as engine_class:
            result = self.runner.invoke(app, ["bootstrap"])

        self.assertEqual(result.exit_code, 0)
        self.assertEqual(result.output, "Bootstrap completed successfully.\n")
        engine_class.return_value.bootstrap.assert_called_once_with(Path("config/core.yaml"))

    def test_bootstrap_command_reports_failure_without_cause(self) -> None:
        with patch("tasc_cli.commands.bootstrap.BootstrapEngine") as engine_class:
            engine_class.return_value.bootstrap.side_effect = BootstrapException(
                "Bootstrap failed",
                "TASC-BOOTSTRAP-0001",
            )

            result = self.runner.invoke(app, ["bootstrap"])

        self.assertNotEqual(result.exit_code, 0)
        self.assertEqual(
            result.output,
            "Bootstrap failed.\n"
            "\n"
            "Reason:\n"
            "\n"
            "[TASC-BOOTSTRAP-0001] Bootstrap failed\n",
        )

    def test_bootstrap_command_reports_root_cause(self) -> None:
        with patch("tasc_cli.commands.bootstrap.BootstrapEngine") as engine_class:
            engine_class.return_value.bootstrap.side_effect = BootstrapException(
                "Bootstrap failed",
                "TASC-BOOTSTRAP-0001",
                cause=ConfigurationException("File not found", "TASC-CONFIG-0001"),
            )

            result = self.runner.invoke(app, ["bootstrap"])

        self.assertNotEqual(result.exit_code, 0)
        self.assertEqual(
            result.output,
            "Bootstrap failed.\n"
            "\n"
            "Reason:\n"
            "\n"
            "[TASC-CONFIG-0001] File not found\n",
        )

    def test_bootstrap_command_uses_explicit_config_path(self) -> None:
        config_path = Path("custom/core.yaml")
        with patch("tasc_cli.commands.bootstrap.BootstrapEngine") as engine_class:
            result = self.runner.invoke(app, ["bootstrap", "--config", str(config_path)])

        self.assertEqual(result.exit_code, 0)
        engine_class.return_value.bootstrap.assert_called_once_with(config_path)

    def test_project_create_command(self) -> None:
        with patch("tasc_cli.commands.project.ProjectService") as service_class:
            result = self.runner.invoke(app, ["project", "create", "demo"])

        self.assertEqual(result.exit_code, 0)
        self.assertEqual(result.output, "Project created.\n")
        metadata, configuration = service_class.return_value.create_project.call_args.args
        self.assertEqual(metadata.name, "demo")
        self.assertEqual(configuration.output_directory, "output")

    def test_project_list_command(self) -> None:
        with patch("tasc_cli.commands.project.ProjectService") as service_class:
            service_class.return_value.list_projects.return_value = [
                self._project("first"),
                self._project("second"),
            ]

            result = self.runner.invoke(app, ["project", "list"])

        self.assertEqual(result.exit_code, 0)
        self.assertEqual(result.output, "first\nsecond\n")
        service_class.return_value.list_projects.assert_called_once_with()

    def test_project_show_command(self) -> None:
        with patch("tasc_cli.commands.project.ProjectService") as service_class:
            service_class.return_value.get_project.return_value = self._project("demo")

            result = self.runner.invoke(app, ["project", "show", "demo"])

        self.assertEqual(result.exit_code, 0)
        self.assertIn("Name: demo", result.output)
        self.assertIn("Language: python", result.output)
        service_class.return_value.get_project.assert_called_once_with("demo")

    def test_project_delete_command(self) -> None:
        with patch("tasc_cli.commands.project.ProjectService") as service_class:
            result = self.runner.invoke(app, ["project", "delete", "demo"])

        self.assertEqual(result.exit_code, 0)
        self.assertEqual(result.output, "Project deleted.\n")
        service_class.return_value.delete_project.assert_called_once_with("demo")

    def test_project_command_reports_project_errors(self) -> None:
        with patch("tasc_cli.commands.project.ProjectService") as service_class:
            service_class.return_value.get_project.side_effect = ProjectException(
                "Project not found: demo"
            )

            result = self.runner.invoke(app, ["project", "show", "demo"])

        self.assertNotEqual(result.exit_code, 0)
        self.assertIn("Project not found: demo", result.output)

    @staticmethod
    def _project(name: str) -> Project:
        return Project(
            metadata=ProjectMetadata(
                name=name,
                display_name=name,
                description="",
                version="0.1.0",
                created_at=datetime(2026, 8, 3, 12, 0, tzinfo=timezone.utc),
            ),
            configuration=ProjectConfiguration(
                language="python",
                framework="none",
                runtime="python",
                output_directory="output",
            ),
        )

    def test_doctor_command_reports_healthy_environment(self) -> None:
        with (
            patch("tasc_cli.commands.doctor.sys.version_info", (3, 12, 0)),
            patch("tasc_cli.commands.doctor.Path.exists", return_value=True),
            patch("tasc_cli.commands.doctor.ConfigurationLoader") as loader_class,
            patch("tasc_cli.commands.doctor.ConfigurationParser") as parser_class,
            patch("tasc_cli.commands.doctor.ConfigurationValidator"),
            patch(
                "tasc_cli.commands.doctor.importlib.import_module",
                return_value=object(),
            ),
        ):
            loader_class.return_value.load.return_value = "configuration"
            parser_class.return_value.parse.return_value = {}
            result = self.runner.invoke(app, ["doctor"])

        self.assertEqual(result.exit_code, 0)
        self.assertIn("[PASS] Python Version", result.output)
        self.assertIn("[PASS] Workspace", result.output)
        self.assertIn("[PASS] Core Configuration", result.output)
        self.assertIn("[PASS] Core Package", result.output)
        self.assertIn("HEALTHY", result.output)

    def test_doctor_command_reports_missing_workspace(self) -> None:
        with (
            patch("tasc_cli.commands.doctor.Path.exists", return_value=False),
            patch("tasc_cli.commands.doctor.ConfigurationLoader") as loader_class,
            patch("tasc_cli.commands.doctor.ConfigurationParser") as parser_class,
            patch("tasc_cli.commands.doctor.ConfigurationValidator"),
            patch(
                "tasc_cli.commands.doctor.importlib.import_module",
                return_value=object(),
            ),
        ):
            loader_class.return_value.load.return_value = "configuration"
            parser_class.return_value.parse.return_value = {}
            result = self.runner.invoke(app, ["doctor"])

        self.assertEqual(result.exit_code, 1)
        self.assertIn("[FAIL] Workspace", result.output)
        self.assertIn("UNHEALTHY", result.output)

    def test_doctor_command_reports_missing_core_configuration(self) -> None:
        with (
            patch("tasc_cli.commands.doctor.Path.exists", return_value=True),
            patch("tasc_cli.commands.doctor.ConfigurationLoader") as loader_class,
            patch(
                "tasc_cli.commands.doctor.importlib.import_module",
                return_value=object(),
            ),
        ):
            loader_class.return_value.load.side_effect = ConfigurationException(
                "File not found",
                "TASC-CONFIG-0001",
            )
            result = self.runner.invoke(app, ["doctor"])

        self.assertEqual(result.exit_code, 1)
        self.assertIn("[FAIL] Core Configuration", result.output)
        self.assertIn("File not found", result.output)

    def test_doctor_command_reports_invalid_core_configuration(self) -> None:
        with (
            patch("tasc_cli.commands.doctor.Path.exists", return_value=True),
            patch("tasc_cli.commands.doctor.ConfigurationLoader") as loader_class,
            patch("tasc_cli.commands.doctor.ConfigurationParser") as parser_class,
            patch(
                "tasc_cli.commands.doctor.ConfigurationValidator"
            ) as validator_class,
            patch(
                "tasc_cli.commands.doctor.importlib.import_module",
                return_value=object(),
            ),
        ):
            loader_class.return_value.load.return_value = "invalid"
            parser_class.return_value.parse.return_value = {}
            validator_class.return_value.validate.side_effect = ValidationException(
                "Invalid configuration",
                "TASC-VALIDATION-0004",
            )
            result = self.runner.invoke(app, ["doctor"])

        self.assertEqual(result.exit_code, 1)
        self.assertIn("[FAIL] Core Configuration", result.output)
        self.assertIn("Invalid configuration", result.output)

    def test_doctor_command_reports_missing_core_package(self) -> None:
        with (
            patch("tasc_cli.commands.doctor.Path.exists", return_value=True),
            patch("tasc_cli.commands.doctor.ConfigurationLoader") as loader_class,
            patch("tasc_cli.commands.doctor.ConfigurationParser") as parser_class,
            patch("tasc_cli.commands.doctor.ConfigurationValidator"),
            patch(
                "tasc_cli.commands.doctor.importlib.import_module",
                side_effect=ImportError,
            ),
        ):
            loader_class.return_value.load.return_value = "configuration"
            parser_class.return_value.parse.return_value = {}
            result = self.runner.invoke(app, ["doctor"])

        self.assertEqual(result.exit_code, 1)
        self.assertIn("[FAIL] Core Package", result.output)

    def test_doctor_command_reports_unsupported_python_version(self) -> None:
        with (
            patch("tasc_cli.commands.doctor.sys.version_info", (3, 11, 0)),
            patch("tasc_cli.commands.doctor.Path.exists", return_value=True),
            patch("tasc_cli.commands.doctor.ConfigurationLoader") as loader_class,
            patch("tasc_cli.commands.doctor.ConfigurationParser") as parser_class,
            patch("tasc_cli.commands.doctor.ConfigurationValidator"),
            patch(
                "tasc_cli.commands.doctor.importlib.import_module",
                return_value=object(),
            ),
        ):
            loader_class.return_value.load.return_value = "configuration"
            parser_class.return_value.parse.return_value = {}
            result = self.runner.invoke(app, ["doctor"])

        self.assertEqual(result.exit_code, 1)
        self.assertIn("[FAIL] Python Version", result.output)


if __name__ == "__main__":
    unittest.main()
